services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # Router HTTPS
      - "traefik.http.routers.nginx-sigr-secure.rule=Host(`alpha.kvernicola.cl`)"
      - "traefik.http.routers.nginx-sigr-secure.entrypoints=websecure"
      - "traefik.http.routers.nginx-sigr-secure.tls=true"
      - "traefik.http.routers.nginx-sigr-secure.tls.certresolver=letsencrypt"
      # Router HTTP (redirect a HTTPS)
      - "traefik.http.routers.nginx-sigr.rule=Host(`alpha.kvernicola.cl`)"
      - "traefik.http.routers.nginx-sigr.entrypoints=web"
      - "traefik.http.routers.nginx-sigr.middlewares=redirect-to-https"
      # Middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # Service
      - "traefik.http.services.nginx-sigr.loadbalancer.server.port=80"
      - "traefik.docker.network=dokploy-network"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - restaurant-network
      - dokploy-network

networks:
  restaurant-network:
    external: true
  dokploy-network:
    external: true
